### PR TITLE
Safari also supports time travel through $1, $2, ...

### PR DESCRIPTION
**Pull request by pankajparashar**
More info here, 
https://www.canidev.tools/get-selected-node/safari

### CODE REVIEW

**Comment by pankajparashar** [comment]
Interestingly it doesn't seem to work anymore in the latest version of Safari anymore. Even though it is listed in the Web inspector guide,

Screenshot 2022-09-20 at 15 40 27

**Comment by pankajparashar** [comment]
Closing this, since it no longer works. The documentation is probably outdated.

**Comment by dcrousso** [comment]
@pankajparashar Safari Web Inspector definitely still supports `$1`, `$2`, ..., `$n` \<[https://webkit.org/web-inspector/console-command-line-api/#$1]()>

**Comment by pankajparashar** [comment]
@dcrousso Any ideas what am I doing wrong here? (see GIF below from Safari 16.1)

Expected: $0 = h1, $1 = div, $2 = body
     Actual: $0 = h1, $1 = h1,  $2 = Error!

ScreenFlow

**Comment by dcrousso** [comment]
oooohh interesting it's _DOM_ history

Safari Web Inspector treats `$1`, `$2`, ..., `$n` as _evaluation_ history:
```
> 42
< 42  // $1

> $1 * 2
< 84  // $2

> $2 + 3
< 87  // $3
```

**Comment by pankajparashar** [comment]
Alright, so it appears that Safari no longer allows travelling through selected nodes in the Console. So this is PR is not valid. Thanks.

**Comment by captainbrosset** [comment]
Thanks for figuring this out folks. I would still be interesting to document the safari $1,2,3,...n tip on the site though.

**Comment by pankajparashar** [comment]
@captainbrosset Yeah sure. I'll try to send a PR this weekend. 

AFAIK, no other browser except Safari allows travelling through evaluation history like $1, $2, .... We can only get the last evaluated value using, `$_`, correct?

**Comment by captainbrosset** [comment]
That's my understanding as well.

**Comment by captainbrosset** [comment]
> @captainbrosset Yeah sure. I'll try to send a PR this weekend.

Thanks for proposing, but don't sweat about it. I'll do something quick now.

**Comment by captainbrosset** [comment]
https://devtoolstips.org/tips/en/access-recent-console-results/

**Pull request closed without merging**
